// angular-chat/src/app/message/message-input/message-input.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { Importance } from '../../../models/message.model';

@Component({
    selector: 'app-message-input',
    templateUrl: './message-input.component.html'
})
export class MessageInputComponent {
    messageText: string = '';
    importance: Importance = 'normal';
    color: string = '#000000';

    @Output() send = new EventEmitter<{ text: string; importance: Importance; color: string }>();

    onSubmit(): void {
        if (!this.messageText.trim()) return;
        this.send.emit({ text: this.messageText, importance: this.importance, color: this.color });
        this.messageText = '';
    }
}

<form (ngSubmit)="onSubmit()" class="d-flex gap-2 mt-3">
    <input [(ngModel)]="messageText" type="text" class="form-control" id="messageText" name="messageText"
        placeholder="Votre message..." required>

    <select [(ngModel)]="importance" class="form-select w-auto" id="importance" name="importance">
        <option value="normal">Normal</option>
        <option value="important">Important</option>
        <option value="urgent">Urgent</option>
    </select>

    <input [(ngModel)]="color" type="color" class="form-control form-control-color w-1" id="color" name="color">

    <button [disabled]="!messageText.trim()" type="submit" class="btn btn-success">ENVOYER</button>
</form>

// svelte-chat/src/lib/components/MessageInput.svelte
<script lang="ts">
  import type { Importance } from "$lib/models/message";
  import { createEventDispatcher } from "svelte";

  const dispatch = createEventDispatcher();

  export let socket: any;
  export let username: string;

  let messageText = "";
  let importance: Importance = "normal";
  let color = "#000000";

  let typingTimeout: any;

  function sendMessage() {
    if (!messageText.trim()) return;

    socket.emit("message", {
      message: messageText,
      importance,
      color,
    });

    messageText = "";
    socket.emit("typing", false);
  }

  function handleTyping() {
    socket.emit("typing", true);

    clearTimeout(typingTimeout);
    typingTimeout = setTimeout(() => {
      socket.emit("typing", false);
    }, 1000);
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === "Enter") {
      sendMessage();
    }
  }
</script>

<div class="input-group mt-2">
  <input
    class="form-control w-75"
    placeholder="Tapez votre message..."
    bind:value={messageText}
    on:input={handleTyping}
    on:keydown={handleKeyDown}
  />

  <select class="form-select" bind:value={importance} style="max-width: 120px;">
    <option value="normal">Normal</option>
    <option value="important">Important</option>
    <option value="urgent">Urgent</option>
  </select>

  <input
    type="color"
    class="form-control form-control-color"
    bind:value={color}
  />

  <button class="btn btn-primary" on:click={sendMessage}>Envoyer</button>
</div>
